vich_uploader:
    db_driver: orm

    mappings:
        user_photo:
            uri_prefix: /user-photo
            upload_destination: '%kernel.project_dir%/public/user_photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
