version: "3.7"

services:
  nginx:
    build:
      context: ./nginx
      args:
        SERVER_NAME: simply.loc
        PHP_FPM_ADDRESS: php
        PHP_FPM_PORT: 9000
    ports:
      - "80:80"
    working_dir: /app
    volumes:
      - ../:/app
    depends_on:
      - php

  php:
    build:
      context: ./php
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /app
    volumes:
      - ../:/app
      - ./php/php.ini:/usr/local/etc/php/php.ini

  postgres:
    image: postgres:alpine3.14
    environment:
      POSTGRES_DB: 'simply'
      POSTGRES_USER: 'simply'
      POSTGRES_PASSWORD: 'simply'
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data

  node:
    build:
      context: ./node
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ../:/app
    command: bash -c "yarn install && yarn watch"
    depends_on:
      - php

volumes:
  db_data: ~